//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaMagisterska.BazaDanych
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gracz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gracz()
        {
            this.UczestnicyGry = new HashSet<UczestnikGry>();
        }
    
        public long Id { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string NrLicencji { get; set; }
        public byte Pozycja { get; set; }
        public bool CzyUsuniety { get; set; }
        public Nullable<long> KlubId { get; set; }
        public long UzytkownikId { get; set; }
        public byte KategoriaWiekowa { get; set; }
        public byte Plec { get; set; }
    
        public virtual Klub Klub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UczestnikGry> UczestnicyGry { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
    }
}
