//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaMagisterska.BazaDanych
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notatka
    {
        public long Id { get; set; }
        public string Temat { get; set; }
        public string Tresc { get; set; }
        public bool CzyUsuniete { get; set; }
        public System.DateTime DataDodania { get; set; }
        public long UzytkownikId { get; set; }
    
        public virtual Uzytkownik Uzytkownik { get; set; }
    }
}
