//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaMagisterska.BazaDanych
{
    using System;
    using System.Collections.Generic;
    
    public partial class OcenaGracza
    {
        public long Id { get; set; }
        public byte Ocena { get; set; }
        public long UczestnikGryId { get; set; }
        public byte NumerZadania { get; set; }
        public Nullable<byte> DecyzjaGracza { get; set; }
        public Nullable<byte> DecyzjaTrenera { get; set; }
        public byte NumerRundy { get; set; }
    
        public virtual UczestnikGry UczestnikGry { get; set; }
    }
}
