//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaMagisterska.BazaDanych
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PracaMagisterskaEntities : DbContext
    {
        public PracaMagisterskaEntities()
            : base("name=PracaMagisterskaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gracz> Gracz { get; set; }
        public virtual DbSet<Klub> Klub { get; set; }
        public virtual DbSet<Uzytkownik> Uzytkownik { get; set; }
        public virtual DbSet<Gra> Gra { get; set; }
        public virtual DbSet<UczestnikGry> UczestnikGry { get; set; }
    }
}
