//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaMagisterska.BazaDanych
{
    using System;
    using System.Collections.Generic;
    
    public partial class UczestnikGry
    {
        public long Id { get; set; }
        public long GraczId { get; set; }
        public string ImiePrzeciwnika { get; set; }
        public string NazwiskoPrzeciwnika { get; set; }
        public long GraId { get; set; }
        public bool CzyUsuniety { get; set; }
    
        public virtual Gra Gra { get; set; }
        public virtual Gracz Gracz { get; set; }
    }
}
